CREATE DATABASE IF NOT EXISTS QuanLyVatTu;
USE QuanLyVatTu;

-- 1. Bảng PHIEUXUAT
CREATE TABLE PHIEUXUAT (
    SoPX VARCHAR(20) PRIMARY KEY,
    NgayXuat DATETIME NOT NULL
);

-- 2. Bảng VATTU
CREATE TABLE VATTU (
    MaVTU VARCHAR(20) PRIMARY KEY,
    TenVTU VARCHAR(100) NOT NULL
);

-- 3. Bảng PHIEUNHAP
CREATE TABLE PHIEUNHAP (
    SoPN VARCHAR(20) PRIMARY KEY,
    NgayNhap DATETIME NOT NULL
);

-- 4. Bảng NHA_CC
CREATE TABLE NHA_CC (
    MaNCC VARCHAR(20) PRIMARY KEY,
    TenNCC VARCHAR(100) NOT NULL,
    DiaChi VARCHAR(200)
);

-- 5. Bảng đa trị Số điện thoại Nhà cung cấp
CREATE TABLE NHACC_SDT (
    MaNCC VARCHAR(20),
    SDT VARCHAR(15),
    PRIMARY KEY (MaNCC, SDT),
    CONSTRAINT FK_SDT_NHACC FOREIGN KEY (MaNCC) REFERENCES NHA_CC(MaNCC) ON DELETE CASCADE
);

-- 6. Bảng DONDH (Mối quan hệ 1-N với NHA_CC)
CREATE TABLE DONDH (
    SoDH VARCHAR(20) PRIMARY KEY,
    NgayDH DATETIME NOT NULL,
    MaNCC VARCHAR(20) NOT NULL,
    CONSTRAINT FK_DONDH_NHACC FOREIGN KEY (MaNCC) REFERENCES NHA_CC(MaNCC)
);

-- 7. Bảng Chi tiết Phiếu xuất (Mối quan hệ N-M)
CREATE TABLE CHI_TIET_PHIEU_XUAT (
    SoPX VARCHAR(20),
    MaVTU VARCHAR(20),
    DGXuat DECIMAL(18, 2) NOT NULL CHECK (DGXuat >= 0),
    SLXuat INT NOT NULL CHECK (SLXuat > 0),
    PRIMARY KEY (SoPX, MaVTU),
    CONSTRAINT FK_CTPX_PHIEUXUAT FOREIGN KEY (SoPX) REFERENCES PHIEUXUAT(SoPX),
    CONSTRAINT FK_CTPX_VATTU FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);

-- 8. Bảng Chi tiết Phiếu nhập (Mối quan hệ N-M)
CREATE TABLE CHI_TIET_PHIEU_NHAP (
    SoPN VARCHAR(20),
    MaVTU VARCHAR(20),
    DGNhap DECIMAL(18, 2) NOT NULL CHECK (DGNhap >= 0),
    SLNhap INT NOT NULL CHECK (SLNhap > 0),
    PRIMARY KEY (SoPN, MaVTU),
    CONSTRAINT FK_CTPN_PHIEUNHAP FOREIGN KEY (SoPN) REFERENCES PHIEUNHAP(SoPN),
    CONSTRAINT FK_CTPN_VATTU FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);

-- 9. Bảng Chi tiết Đơn hàng (Mối quan hệ N-M)
CREATE TABLE CHI_TIET_DON_HANG (
    SoDH VARCHAR(20),
    MaVTU VARCHAR(20),
    PRIMARY KEY (SoDH, MaVTU),
    CONSTRAINT FK_CTDH_DONDH FOREIGN KEY (SoDH) REFERENCES DONDH(SoDH),
    CONSTRAINT FK_CTDH_VATTU FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);